const {test,expect}=require('@playwright/test');
const AxeBuilder=require('@axe-core/playwright').default;
const {uniqueId,registerUser,createGame,startGame,dismissFirstRunGuidance,focusHomeworld}=require('./support/ui-game-harness');
test('planet inspection, capacity, countdown and centered probe are readable',async({page},info)=>{
 test.setTimeout(150000);page.setDefaultTimeout(10000);
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const username=uniqueId('planet');await registerUser(page,{username,email:username+'@example.com',password:'Secure123!'});
 await createGame(page,uniqueId('survey'),{maxPlayers:'2',mode:'test'});await startGame(page,[page]);
 await page.locator('#tour-skip').waitFor({state:'visible',timeout:15000});await dismissFirstRunGuidance(page);await focusHomeworld(page);
 await expect(page.locator('#planetCapacityStatus')).toBeVisible();
 await expect(page.locator('#planetCapacityStatus strong')).toContainText('building slots free');
 expect(await page.locator('#turnRedFlashWhenLow').evaluate(el=>parseFloat(getComputedStyle(el).fontSize))).toBeGreaterThanOrEqual(24);
 await expect(page.locator('#inspectPlanetBtn')).toBeVisible({timeout:45000});
 await page.locator('#inspectPlanetBtn').click();
 await expect(page.locator('#planetInspection')).toBeVisible();
 await expect(page.locator('#exitPlanetInspection')).toBeFocused();
 await page.waitForTimeout(1500);
 await page.screenshot({path:info.outputPath('planet-desktop.png')});
 const audit=await new AxeBuilder({page}).include('#planetInspection').analyze();expect(audit.violations).toEqual([]);
 await page.setViewportSize({width:390,height:844});await page.waitForTimeout(600);
 await page.screenshot({path:info.outputPath('planet-mobile.png')});
 await page.keyboard.press('Escape');await expect(page.locator('#planetInspection')).toBeHidden();
 await expect(page.locator('#inspectPlanetBtn')).toBeFocused();
 await page.waitForTimeout(500);
 await page.screenshot({path:info.outputPath('returned-mobile.png')});await page.locator('#inspectPlanetBtn').click();
 await page.setViewportSize({width:667,height:375});await page.waitForTimeout(400);
 await expect(page.locator('#exitPlanetInspection')).toBeInViewport({ratio:1});
 await page.locator('#exitPlanetInspection').click();await expect(page.locator('#planetInspection')).toBeHidden();
 await expect(page.locator('#nextTurnBtn')).toBeFocused();
 await page.setViewportSize({width:390,height:844});
 await page.evaluate(()=>renderProbeSuggestionCard('Scan sector','A probe costs 300 crystals. It may be destroyed.',()=>{},()=>{}));
 const modal=page.locator('#probeSuggestionCard');await expect(modal).toBeVisible();await expect(modal).toHaveAccessibleName('Scan sector');
 const box=await modal.boundingBox();expect(Math.abs(box.x+box.width/2-195)).toBeLessThan(2);expect(Math.abs(box.y+box.height/2-422)).toBeLessThan(2);
 await page.screenshot({path:info.outputPath('probe-mobile.png')});
 expect((await new AxeBuilder({page}).include('#probeSuggestionCard').analyze()).violations).toEqual([]);
 await page.keyboard.press('Escape');await expect(modal).toHaveCount(0);
 const diagnostics=await page.evaluate(()=>window.Galaxy3D.debugRenderPath());
 await info.attach('renderer-diagnostics',{body:JSON.stringify(diagnostics,null,2),contentType:'application/json'});
 await page.setViewportSize({width:1280,height:720});
 await page.evaluate(async()=>{
  await import('/js/battle3d.js?v=20260906');
  const fields=new Array(40).fill(0);fields[0]=4;fields[9]=4;fields[20]=2;fields[29]=0;
  window.Battle3D.createBattleVisualization('battle:'+fields.join(':'),{attackerRaceId:4,defenderRaceId:7,viewerRole:'attacker',sectorId:1,planetType:8,durationMs:30000});
 });
 await expect(page.locator('#battleTheater.on canvas')).toBeVisible({timeout:15000});
 await page.waitForTimeout(1200);await page.screenshot({path:info.outputPath('faction-battle.png')});
 await page.evaluate(()=>window.Battle3D.cleanupBattleVisualization());
 expect(errors).toEqual([]);
});
